// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "(WQVQPOOOOQO'#Ci'#CiOeQPO'#C_OsQPO'#C`OOQO'#C`'#C`O!RQPO'#CaO!^QPO'#CnOOQO'#Cn'#CnOOQO'#C_'#C_O!cQPO'#C_OOQO'#Ch'#ChQVQPOOOOQO-E6g-E6gOOQO,58y,58yO!kQPO,58yO#XQQO,58{O#cQPO,59YOOQO-E6f-E6fOOQO1G.e1G.eOOQO'#Ce'#CeO#qQPO'#CrOOQO'#Cg'#CgOOQO'#Cr'#CrO$VQPO'#CcO$eQPO1G.gO$pQPO1G.tOOQO'#Cb'#CbOOQO1G.t1G.tO%OQPO,59OO%WQPO,59OP%`QPO'#CiO!sQQO'#CjO%hQPO,58}O%vQPO7+$ROOQO7+$`7+$`O&RQPO1G.jO&RQPO1G.jO&ZQPO1G.jP!sQQO,59UO!sQQO,59UOOQO,59U,59UOOQO-E6h-E6hO&cQPO7+$UO&kQPO7+$UO&kQPO7+$UOOQO7+$U7+$UP!sQQO1G.pOOQO1G.p1G.pO&sQPO<<GpO&sQPO<<GpOOQO<<Gp<<GpPOQO7+$[7+$[O&{QPOAN=[OOQOAN=[AN=[OOQOG22vG22v",
  stateData: "'_~OPOS~OaPOcROdSOmWO~OaPOcROdSOm]O~OaUXeSXmUXnUX~OaPOmTXnTX~Oe`O~Om]On]O~OmbOnbO~OYfOaPOceOgcOhcOkeO~OmTanTa~P!sOaPOcjOmbanba~OaPOimOafXlfXmfXnfX~OloOaVXmVXnVX~OaPOmTinTi~OaPOcjOmbinbi~OaPOisO~OYuOaPO~OaPOlvO~OloOaVamVanVa~OaPOmTqnTq~OY{OaPO~OaPOj}O~OY!QOaPO~OaPOj!SO~OaPOj!VO~OaPOj!WO~OYgkhcPmac~",
  goto: "$^gPPPhlq|!T!W!_P!W!f!l#rPPP#xPPP$PTYOZVUOQZUVOQZQk`RriZTOQZ`iRh_Zf_ovw!OZd_ovw!OQZORaZSQOZj[Q_ilnqtwz|!O!R!UQ_TQi`QldQqhQtmQwoQzsQ|uQ!OvQ!R{R!U!QQpgRypSXOZR^QQg_QxoS!PvwR!T!O",
  nodeNames: "⚠ Comment Program Statement LabelDef MacroExpr MacroName ArgList ImmRegister Immediate Register LabelName",
  maxTerm: 30,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "1s~RnXY#PYZ#U]^#Zpq#Pst#ctu#}xy$fyz$k{|$p|}&W}!O$p!O!P#}!Q!R&]!R!['`![!]'p!c!}#}#R#S#}#T#U'u#U#Y#}#Y#Z)a#Z#[)a#[#f#}#f#g*O#g#h*j#h#i,e#i#l#}#l#m-i#m#n#}#n#o/s~~1n~#UOa~~#ZOm~~#`Pm~YZ#U~#hTP~OY#cZ]#c^;'S#c;'S;=`#w<%lO#c~#zP;=`<%l#c~$SUc~tu#}!O!P#}!Q![#}!c!}#}#R#S#}#T#o#}~$kOi~~$pOj~Q$sQ!Q!R$y!R![%dQ%ORhQ!Q!Y%X!Y![%d#l#m%lQ%^QhQ!Q!Y%X!Y![%dQ%iPhQ!Q![%dQ%oR!Q![%x!c!i%x#T#Z%xQ%}RhQ!Q![%x!c!i%x#T#Z%x~&]Ol~R&dTdPhQ!Q!Y%X!Y![%d#U#V&s#Y#Z'Z#l#m%lQ&xQkQ!Q!R'O!R!S'OQ'TQgQ!Q!R'O!R!S'OQ'`OkQR'gRdPhQ!Q![%d#U#V'Z#Y#Z'Z~'uOe~~'z^c~tu#}!O!P#}!Q!R(v!R!S(v!S!T(v!T!U(v!U!V(v!V!W(v!W!X(v!X!Y(v!Y![#}!c!}#}#R#S#}#T#o#}~(}UY~c~tu#}!O!P#}!Q![#}!c!}#}#R#S#}#T#o#}~)fWc~tu#}!O!P#}!Q![#}!c!}#}#R#S#}#T#d#}#d#e(v#e#o#}~*TVc~tu#}!O!P#}!Q![#}!c!}#}#R#S#}#T#U(v#U#o#}~*oac~tu#}!O!P#}!Q!R(v!R!S+t!S!T(v!T!U(v!U!V(v!V!W(v!W!X(v!X!Y(v!Y!Z(v!Z![(v!c!}#}#R#S#}#T#d#}#d#e(v#e#o#}~+{WY~c~tu#}!O!P#}!Q!R(v!R!S(v!S![#}!c!}#}#R#S#}#T#o#}~,j_c~tu#}!O!P#}!Q!R(v!R!S(v!S!T(v!T!U(v!U!V(v!V!W(v!W!X(v!X![#}!c!}#}#R#S#}#T#d#}#d#e(v#e#o#}~-n_c~tu#}!O!P#}!Q!R(v!R!S.m!S!T.m!T!U+t!U!V(v!V!W(v!W!X(v!X!Y(v!Y!Z(v!Z![(v!c!}#}#R#S#}#T#o#}~.t_Y~c~tu#}!O!P#}!Q!R(v!R!S(v!S!T(v!T!U(v!U!V(v!V!W(v!W!X(v!X!Y(v!Y!Z(v!Z![(v!c!}#}#R#S#}#T#o#}~/xWc~tu#}!O!P#}!Q![#}!c!}#}#R#S#}#T#X#}#X#Y0b#Y#o#}~0gWc~tu#}!O!P#}!Q![#}!c!}#}#R#S#}#T#f#}#f#g1P#g#o#}~1UWc~tu#}!O!P#}!Q![#}!c!}#}#R#S#}#T#c#}#c#d(v#d#o#}~1sOn~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  tokenPrec: 281
})
