// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "(jQVQPOOOOQO'#Ci'#CiObQPO'#ChOmQPO'#C`OxQPO'#CaO!QQPO'#C_O!VQPO'#C_OOQO'#Ch'#ChQVQPOOOOQO-E6g-E6gO![QPO,58yO!aQPO,58yOOQO,59S,59SO!fQPO,58{O!wQPO,58yOOQO,58y,58yOOQO-E6f-E6fO#PQPO1G.eOOQO1G.e1G.eO#XQPO'#CqOOQO'#Cg'#CgOOQO'#Cq'#CqO#jQPO'#CcO#uQPO1G.gO#}QPO1G.eO$YQPO7+$POOQO7+$P7+$PO$eQPO,59OO$mQPO,59OP$uQPO'#CiO$}QPO'#CjO%]QPO,58}O%hQPO7+$ROOQO'#Cb'#CbO%pQPO7+$POOQO<<Gk<<GkO%uQPO<<GkO%zQPO1G.jO%zQPO1G.jO&SQPO1G.jP$}QPO,59UO$}QPO,59UOOQO,59U,59UOOQO-E6h-E6hOOQOAN=VAN=VO&[QPO7+$UO&dQPO7+$UO&dQPO7+$UOOQO7+$U7+$UP$}QPO1G.pOOQO1G.p1G.pO&lQPO<<GpO&lQPO<<GpOOQO<<Gp<<GpPOQO7+$[7+$[O&tQPOAN=[OOQOAN=[AN=[OOQOG22vG22v",
  stateData: "'U~OPOS~OaPObVOcRO~OaPOb[OcRO~OaUXbUXdSX~OaPObTX~Od^O~Ob_O~OdaO~ObbO~OXcOYeOaPOcdObTa~OaPObbO~OaPObjO~OaPOflOaeXbeXheX~OhnOaVXbVX~OaPObTi~OaPObjOcqO~OaPObsOcqO~OaPOfuO~OYwOaPO~OaPOhxO~OXcOYeOaPOcdO~OhnOaVabVa~OaPObTq~ObsO~Ob|O~OY!OOaPO~OaPOg!QO~OY!TOaPO~OaPOg!VO~OaPOg!YO~OaPOg!ZO~OYXcPbaP~",
  goto: "$VfPPPgkr!P!W!ZPP!Z!b!h#rPPPPPP#xTVOWSTOWRYQSUOWQZQQrhRtiZSOQWhiRg]Ze]nxy!RQWOR`WSQOWlXQ]hikmpvy}!P!R!U!XQ]SQh^QiaQkcQpgQvlQynQ}uQ!PwQ!RxQ!U!OR!X!TQofR{oQf]QznS!SxyR!W!R",
  nodeNames: "⚠ Comment Program Statement LabelDef MacroExpr MacroName ArgList ImmRegister Immediate Register LabelName",
  maxTerm: 24,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "0o~RmXY!|YZ#R]^#Wpq!|st#`tu#zxy$cyz$h{|$m|}&l}!O$m!O!P#z!Q!R$v!R![%d![!]&q!c!}#z#R#S#z#T#U&v#U#Y#z#Y#Z(b#Z#[(b#[#f#z#f#g)P#g#h)k#h#i+f#i#l#z#l#m,j#m#n#z#n#o.t~#ROa~~#WOb~~#]Pb~YZ#R~#eTP~OY#`Z]#`^;'S#`;'S;=`#t<%lO#`~#wP;=`<%l#`~$PUc~tu#z!O!P#z!Q![#z!c!}#z#R#S#z#T#o#z~$hOf~~$mOg~~$pQ!Q!R$v!R![%d~${SX~!Q!Y%X!Y![%d#U#V%l#l#m&Q~%^QX~!Q!Y%X!Y![%d~%iPX~!Q![%d~%oQ!Q!R%u!R!S%u~%zQX~!Q!R%u!R!S%u~&TR!Q![&^!c!i&^#T#Z&^~&cRX~!Q![&^!c!i&^#T#Z&^~&qOh~~&vOd~~&{^c~tu#z!O!P#z!Q!R'w!R!S'w!S!T'w!T!U'w!U!V'w!V!W'w!W!X'w!X!Y'w!Y![#z!c!}#z#R#S#z#T#o#z~(OUY~c~tu#z!O!P#z!Q![#z!c!}#z#R#S#z#T#o#z~(gWc~tu#z!O!P#z!Q![#z!c!}#z#R#S#z#T#d#z#d#e'w#e#o#z~)UVc~tu#z!O!P#z!Q![#z!c!}#z#R#S#z#T#U'w#U#o#z~)pac~tu#z!O!P#z!Q!R'w!R!S*u!S!T'w!T!U'w!U!V'w!V!W'w!W!X'w!X!Y'w!Y!Z'w!Z!['w!c!}#z#R#S#z#T#d#z#d#e'w#e#o#z~*|WY~c~tu#z!O!P#z!Q!R'w!R!S'w!S![#z!c!}#z#R#S#z#T#o#z~+k_c~tu#z!O!P#z!Q!R'w!R!S'w!S!T'w!T!U'w!U!V'w!V!W'w!W!X'w!X![#z!c!}#z#R#S#z#T#d#z#d#e'w#e#o#z~,o_c~tu#z!O!P#z!Q!R'w!R!S-n!S!T-n!T!U*u!U!V'w!V!W'w!W!X'w!X!Y'w!Y!Z'w!Z!['w!c!}#z#R#S#z#T#o#z~-u_Y~c~tu#z!O!P#z!Q!R'w!R!S'w!S!T'w!T!U'w!U!V'w!V!W'w!W!X'w!X!Y'w!Y!Z'w!Z!['w!c!}#z#R#S#z#T#o#z~.yWc~tu#z!O!P#z!Q![#z!c!}#z#R#S#z#T#X#z#X#Y/c#Y#o#z~/hWc~tu#z!O!P#z!Q![#z!c!}#z#R#S#z#T#f#z#f#g0Q#g#o#z~0VWc~tu#z!O!P#z!Q![#z!c!}#z#R#S#z#T#c#z#c#d'w#d#o#z",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 274
})
