// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  program = 1,
  Statement = 2,
  LabelDef = 3,
  MacroExpr = 4,
  MacroName = 5,
  ArgList = 6,
  ImmRegister = 7,
  Immediate = 8,
  Register = 9,
  LabelName = 10
