// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Statement = 3,
  LabelDef = 4,
  MacroExpr = 5,
  MacroName = 6,
  ArgList = 7,
  ImmRegister = 8,
  Immediate = 9,
  Register = 10,
  LabelName = 11
