// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "(jQVQPOOOOQO'#Ci'#CiObQPO'#ChOmQPO'#C`OxQPO'#CaO!QQPO'#C_O!VQPO'#C_OOQO'#Ch'#ChQVQPOOOOQO-E6g-E6gO![QPO,58yO!aQPO,58yOOQO,59S,59SO!fQPO,58{O!wQPO,58yOOQO,58y,58yOOQO-E6f-E6fO#PQPO1G.eOOQO1G.e1G.eO#XQPO'#CqOOQO'#Cg'#CgOOQO'#Cq'#CqO#jQPO'#CcO#uQPO1G.gO#}QPO1G.eO$YQPO7+$POOQO7+$P7+$PO$eQPO,59OO$mQPO,59OP$uQPO'#CiO$}QPO'#CjO%]QPO,58}O%hQPO7+$ROOQO'#Cb'#CbO%pQPO7+$POOQO<<Gk<<GkO%uQPO<<GkO%zQPO1G.jO%zQPO1G.jO&SQPO1G.jP$}QPO,59UO$}QPO,59UOOQO,59U,59UOOQO-E6h-E6hOOQOAN=VAN=VO&[QPO7+$UO&dQPO7+$UO&dQPO7+$UOOQO7+$U7+$UP$}QPO1G.pOOQO1G.p1G.pO&lQPO<<GpO&lQPO<<GpOOQO<<Gp<<GpPOQO7+$[7+$[O&tQPOAN=[OOQOAN=[AN=[OOQOG22vG22v",
  stateData: "'U~OPOS~OaPObVOcRO~OaPOb[OcRO~OaUXbUXdSX~OaPObTX~Od^O~Ob_O~OdaO~ObbO~OXcOYeOaPOcdObTa~OaPObbO~OaPObjO~OaPOflOaeXbeXheX~OhnOaVXbVX~OaPObTi~OaPObjOcqO~OaPObsOcqO~OaPOfuO~OYwOaPO~OaPOhxO~OXcOYeOaPOcdO~OhnOaVabVa~OaPObTq~ObsO~Ob|O~OY!OOaPO~OaPOg!QO~OY!TOaPO~OaPOg!VO~OaPOg!YO~OaPOg!ZO~OYXcPbaP~",
  goto: "$VfPPPgkr!P!W!ZPP!Z!b!h#rPPPPPP#xTVOWSTOWRYQSUOWQZQQrhRtiZSOQWhiRg]Ze]nxy!RQWOR`WSQOWlXQ]hikmpvy}!P!R!U!XQ]SQh^QiaQkcQpgQvlQynQ}uQ!PwQ!RxQ!U!OR!X!TQofR{oQf]QznS!SxyR!W!R",
  nodeNames: "⚠ Comment Program Statement LabelDef MacroExpr MacroName ArgList ImmRegister Immediate Register LabelName",
  maxTerm: 24,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "1f~RmXY!|YZ#_]^#rpq!|st$Vtu$qxy%Yyz%_{|%d|}'c}!O%d!O!P$q!Q!R%m!R![&Z![!]'h!c!}$q#R#S$q#T#U'm#U#Y$q#Y#Z)X#Z#[)X#[#f$q#f#g)v#g#h*b#h#i,]#i#l$q#l#m-a#m#n$q#n#o/k~#RSa~XY!|YZ!|]^!|pq!|~#fSb~a~XY!|YZ!|]^!|pq!|~#ySb~a~XY!|YZ#_]^!|pq!|~$[TP~OY$VZ]$V^;'S$V;'S;=`$k<%lO$V~$nP;=`<%l$V~$vUc~tu$q!O!P$q!Q![$q!c!}$q#R#S$q#T#o$q~%_Of~~%dOg~~%gQ!Q!R%m!R![&Z~%rSX~!Q!Y&O!Y![&Z#U#V&c#l#m&w~&TQX~!Q!Y&O!Y![&Z~&`PX~!Q![&Z~&fQ!Q!R&l!R!S&l~&qQX~!Q!R&l!R!S&l~&zR!Q!['T!c!i'T#T#Z'T~'YRX~!Q!['T!c!i'T#T#Z'T~'hOh~~'mOd~~'r^c~tu$q!O!P$q!Q!R(n!R!S(n!S!T(n!T!U(n!U!V(n!V!W(n!W!X(n!X!Y(n!Y![$q!c!}$q#R#S$q#T#o$q~(uUY~c~tu$q!O!P$q!Q![$q!c!}$q#R#S$q#T#o$q~)^Wc~tu$q!O!P$q!Q![$q!c!}$q#R#S$q#T#d$q#d#e(n#e#o$q~){Vc~tu$q!O!P$q!Q![$q!c!}$q#R#S$q#T#U(n#U#o$q~*gac~tu$q!O!P$q!Q!R(n!R!S+l!S!T(n!T!U(n!U!V(n!V!W(n!W!X(n!X!Y(n!Y!Z(n!Z![(n!c!}$q#R#S$q#T#d$q#d#e(n#e#o$q~+sWY~c~tu$q!O!P$q!Q!R(n!R!S(n!S![$q!c!}$q#R#S$q#T#o$q~,b_c~tu$q!O!P$q!Q!R(n!R!S(n!S!T(n!T!U(n!U!V(n!V!W(n!W!X(n!X![$q!c!}$q#R#S$q#T#d$q#d#e(n#e#o$q~-f_c~tu$q!O!P$q!Q!R(n!R!S.e!S!T.e!T!U+l!U!V(n!V!W(n!W!X(n!X!Y(n!Y!Z(n!Z![(n!c!}$q#R#S$q#T#o$q~.l_Y~c~tu$q!O!P$q!Q!R(n!R!S(n!S!T(n!T!U(n!U!V(n!V!W(n!W!X(n!X!Y(n!Y!Z(n!Z![(n!c!}$q#R#S$q#T#o$q~/pWc~tu$q!O!P$q!Q![$q!c!}$q#R#S$q#T#X$q#X#Y0Y#Y#o$q~0_Wc~tu$q!O!P$q!Q![$q!c!}$q#R#S$q#T#f$q#f#g0w#g#o$q~0|Wc~tu$q!O!P$q!Q![$q!c!}$q#R#S$q#T#c$q#c#d(n#d#o$q",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 274
})
