// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Statement = 2,
  LabelDef = 3,
  LabelName = 4,
  MacroExpr = 5,
  MacroName = 6,
  ArgList = 7,
  ImmRegister = 8,
  Immediate = 9,
  Register = 10,
  Comment = 11
