name: Build and Deploy RISC-V Interpreter Web
# attempt 2 gpt4o is stupid
on:
    push:
        branches:
            - main # Adjust this if your default branch is different

jobs:
    # Build job
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Enable Corepack and set Yarn version
              run: |
                  corepack enable
                  corepack prepare yarn@4.4.1 --activate
                  yarn config set enableGlobalCache false

            - name: Install dependencies
              run: yarn install

            - name: Install TypeScript globally (for emsdk workaround)
              run: npm install -g typescript

            - name: Install emsdk
              run: |
                  git clone https://github.com/emscripten-core/emsdk.git
                  cd emsdk
                  ./emsdk install latest
                  ./emsdk activate latest
                  source ./emsdk_env.sh

            - name: Compile WASM
              run: |
                  source ./emsdk/emsdk_env.sh
                  cd rv-interpreter-main
                  emcc -O2 src/interpreter.c src/hash_table.c src/label_table.c -s MODULARIZE=1 -s EXPORT_NAME="MyModule" -s EXPORTED_FUNCTIONS='["_set_register", "_set_memory", "_prepare_code", "_run_code", "_free_code"]' -s "EXTRA_EXPORTED_RUNTIME_METHODS=['FS', 'ccall', 'cwrap']" -s FILESYSTEM=1 -s WASM_BIGINT=1 -s INCOMING_MODULE_JS_API=print,printErr --emit-tsd output.d.ts
                  mv a.out.js ../src/output.js
                  mv a.out.wasm ../src/a.out.wasm
                  mv output.d.ts ../src/output.d.ts

            - name: Build with Parcel
              run: yarn parcel build src/index.html --public-url ./riscv-interpreter-web/

            - name: Move a.out.wasm to dist/src/
              run: |
                  mkdir -p dist/src
                  mv dist/a.out.wasm dist/src/

            - name: Upload artifact for GitHub Pages
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./dist

    # Deploy job
    deploy:
        needs: build
        permissions:
            pages: write # to deploy to Pages
            id-token: write # to verify the deployment originates from an appropriate source

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
